"""Reports HTTP controller: the daily SRE digest (generate-and-copy-for-Slack, no bot/webhook)."""

from __future__ import annotations

from datetime import date

from fastapi import APIRouter, Depends, HTTPException, Query, status

from app.application.incidents.daily_report import DailyReport
from app.domain.users.scope import ProjectScope
from app.interface.http.deps import get_daily_report, get_project_scope, require_role
from app.interface.http.dto.response import DailyReportOut, ReportIncidentOut

router = APIRouter(
    prefix="/api/reports",
    tags=["reports"],
    dependencies=[Depends(require_role("admin", "sre", "consultant"))],
)


@router.get("/daily", response_model=DailyReportOut)
async def get_daily_report_view(
    report_date: date = Query(..., alias="date"),
    service: str | None = Query(default=None),
    force: bool = Query(default=False),
    report: DailyReport = Depends(get_daily_report),
    scope: ProjectScope = Depends(get_project_scope),
) -> DailyReportOut:
    """Roll up `date`'s incidents into a Slack-postable digest (counts + narrative markdown).
    `service` optionally scopes the report to one project. Reloads a previously generated digest
    for the same (date, service) unless `force=true` ("Regenerate report" in the UI).

    Access is checked on the *request* rather than by filtering the result, because a digest is
    cached per (date, service): a filtered one generated by a scoped user would be served back to
    everyone, including admins, as though it covered the whole company. So a scoped user must name
    a project they can see, and only an unrestricted caller may ask for the all-projects digest.
    """
    if not scope.unrestricted:
        if service is None:
            raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN,
                detail="Pick one of your projects — the all-projects digest is admin-only",
            )
        if not scope.allows(service):
            raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN,
                detail=f"You don't have access to '{service}'",
            )
    result = await report.generate(report_date, service=service, force=force)
    return DailyReportOut(
        report_date=result.report_date,
        counts_by_severity=result.counts_by_severity,
        counts_by_status=result.counts_by_status,
        incidents=[
            ReportIncidentOut(
                id=r.id,
                service=r.service,
                status=r.status,
                severity=r.severity,
                summary=r.summary,
                ticket_url=r.ticket_url,
            )
            for r in result.incidents
        ],
        slack_markdown=result.slack_markdown,
    )
